### ISSUE TITLE
YJIT: precise stack scanning for code GC

### ISSUE THREAD

**Issue by maximecb** [Shopify/ruby#456]
Kokubun identified a limitation with the current code GC approach. This is not a critical problem because we can still run several code GC cycles. However, it could be an issue for some very long running programs. It would be nice if we can fix it for 3.2, but if we don't have time, that is an ok answer as well.

Currently, if an ISEQ is on the Ruby stack, we keep all of its code pages alive. The issue is that we are slightly overestimating the amount of live pages, and we may start generating code again for these ISEQs, and said ISEQs may remain on the stack. As such, these ISEQs will accumulate a few extra dead pages at every code GC cycle.

Ideally, we would precisely track which code pages are referenced by C return addresses on the stack, and only keep those specific pages alive. This solves the problem of old versions of C exit code that can't be returned to remaining live.

We use the `jit_return` field to track return addresses for some C function calls (the ones that are re-entrant, not leaves). However, we don't create a Ruby frame for every C function call, in particular leaf functions. I'm wondering if we already create a Ruby frame with a `jit_return` field for every C function that could trigger code GC? Also not sure how Ruby fibers interact with the C stack.

@XrXr @k0kubun

**Comment by k0kubun** [comment]
> However, we don't create a Ruby frame for every C function call, in particular leaf functions.

By its definition, a leaf method doesn't switch to another thread/fiber in the middle of its call. Also, it doesn't trigger code GC because it's a C function. Therefore, I believe it's never on stack when code GC is triggered unless you have multiple Ractors.

Currently, we only use `with_vm_lock` for `rb_yjit_tracing_invalidate_all`, but maybe we should use that for entire `code_gc`. Once we do so, it's guaranteed that such leaf C functions are not on stack while scanning frames even with multiple Ractors. So I think we could deal with it that way.

> Also not sure how Ruby fibers interact with the C stack.

`cont_save_machine_stack` saves a Fiber's C stack to `rb_context_t`. We could let `rb_jit_cont` point to `rb_context_t` or the pointer to its `machine.stack` field instead of `ec` if we want to scan C stack instead of Ruby stack.

**Comment by maximecb** [comment]
> Currently, we only use with_vm_lock for rb_yjit_tracing_invalidate_all, but maybe we should use that for entire code_gc. Once we do so, it's guaranteed that such leaf C functions are not on stack while scanning frames even with multiple Ractors. So I think we could deal with it that way.

That seems workable. Wondering if Alan @XrXr has any input?

> cont_save_machine_stack saves a Fiber's C stack to rb_context_t. We could let rb_jit_cont point to rb_context_t or the pointer to its machine.stack field instead of ec if we want to scan C stack instead of Ruby stack.

Can you explain what is `rb_jit_cont`? Still not clear on how that works.

**Comment by k0kubun** [comment]
> Can you explain what is rb_jit_cont? Still not clear on how that works.

Every Fiber has `rb_context_t` to store its Ruby/C stack. JITs want to check all `rb_context_t`s, but AFAIK there's no way to iterate over all `rb_context_t`s on the interpreter. So we have a doubly-linked list implemented by `rb_jit_cont` to maintain a reference to all `rb_context_t`s. With JIT enabled, whenever a `rb_context_t` is created, a `rb_jit_cont` node holding its reference is created and inserted to the linked list.

For now, each node of the linked list only points to `ec` instead of the entire `rb_context_t` because currently we're only interested in `ec`, but if we want to scan C stack, we could replace the `ec` field with a pointer to C stack information.

**Comment by XrXr** [comment]
We can definitely scan to figure out which pages are on stack, though I think it might not be always correct to just keep on stack pages alive. When the on stack code is close to the end of a page, it jumps to the next page when we resume execution. We need to keep enough metadata to detect this case.

BTW, for scanning, I think leaf functions can be on stack too, even if we take the VM lock. For example, we call `rb_str_intern`, which is leaf, but it takes the VM lock. So if another ractor wins the lock and start code GC, you can have a JIT frame that isn't pointed to by any `jit_return` field. So I think we'd need to scan the C stack for these cases.
