### ISSUE TITLE
YJIT: support calling has_rest iseqs

### ISSUE THREAD

**Issue by k0kubun** [Shopify/ruby#483]
We currently don't compile calls of Ruby methods like:

```rb
def foo(*rest)
  # ...
end
```

which results in side exits that are counted as `send_iseq_has_rest`. This is the top "method call exit reason" in the following benchmarks/applications:

* activerecord: 36%
* liquid-render: 66.2%
* railsbench: 31.4%
* ruby-lsp: 26.6%
* sequel: 45.2%
* SFR: 26.3%
* Core: 22.9%

So implementing it seems important for improving ratio_in_yjit in those benchmarks.

We'd need to implement the same thing as `args_copy` and `args_setup_rest_parameter` in vm_args.c for it.

**Comment by maximecb** [comment]
@jimmyhmiller you said you were starting to look at this?

**Comment by jimmyhmiller** [comment]
Yes, that is my plan for this week

**Comment by maximecb** [comment]
How far along are we on this one @jimmyhmiller ?

**Comment by jimmyhmiller** [comment]
I've made the following PRs related to this issue

https://github.com/ruby/ruby/pull/7311
https://github.com/ruby/ruby/pull/7422
https://github.com/ruby/ruby/pull/7468
https://github.com/ruby/ruby/pull/7499
https://github.com/ruby/ruby/pull/7546
https://github.com/ruby/ruby/pull/7584

Once the latest PR lands, we will really on have 3 unsupported cases for rest params.

```
send_iseq_has_rest_and_captured,
send_iseq_has_rest_and_kw,
send_iseq_has_rest_and_optional
```

I'm hoping to tackle those next and get it so we never unconditionally exit because of rest params.

**Comment by maximecb** [comment]
Great progress. Thanks for the update Jimmy 👍

**Comment by maximecb** [comment]
We miss you @jimmyhmiller !

Hope you're doing well :)

**Comment by jimmyhmiller** [comment]
@maximecb Thanks :)  I miss you all too!

**Comment by maximecb** [comment]
Closing this for now, we can reopen more specific issues later
